update workflow

diff --git a/.github/.workflow/building-block.yaml b/.github/.workflow/building-block.yaml
--- a/.github/.workflow/building-block.yaml
+++ b/.github/.workflow/building-block.yaml
@@ -1,19 +1,19 @@
-name: Building Blocks
+name: Building Block
 
 on: push
 
 jobs:
-  echo-hello:
-    run-on: ubuntu-latest
-    steps:
-      - name: Say hello
-        run: echo "Hello, world!"
+ echo-hello:
+  run-on: ubuntu-latest
+  steps:
+   - name: Say hello
+     run: echo "Hello, world!"
   echo-goodbye:
-    run-on: ubuntu-latest
-    steps: 
-      - name: Failed step
-        run: |
-          echo "I will fail"
-          exit 1
-      - name: Say goodbye
-        run: echo "Goodbye!"
+   run-on: ubuntu-latest
+   steps: 
+    - name: Failed step
+      run: |
+        echo "I will fail"
+        exit 1
+    - name: Say goodbye
+      run: echo "Goodbye!"
