update workflow

diff --git a/.github/.workflow/building-block.yaml b/.github/.workflow/building-block.yaml
--- a/.github/.workflow/building-block.yaml
+++ b/.github/.workflow/building-block.yaml
@@ -3,17 +3,19 @@ name: Building Block
 on: push
 
 jobs:
- echo-hello:
-  runs-on: ubuntu-latest
-  steps:
-   - name: Say hello
-     run: echo "Hello, world!"
+  echo-hello:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Say hello
+        run: echo "Hello, world!"
+
   echo-goodbye:
-   runs-on: ubuntu-latest
-   steps: 
-    - name: Failed step
-      run: |
-        echo "I will fail"
-        exit 1
-    - name: Say goodbye
-      run: echo "Goodbye!"
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failed step
+        run: |
+          echo "I will fail"
+          exit 1
+
+      - name: Say goodbye
+        run: echo "Goodbye!"
